table sales_sample
	lineageTag: 30000000-0000-0000-0000-000000000001

	/// Percentage of total sales revenue contributed by the current product
	measure '% Product Contribution' =
		VAR ProductSales =
			SUMX(
				sales_sample,
				sales_sample[quantity] * sales_sample[unit_price]
			)
	
		VAR TotalSalesAllProducts =
			CALCULATE(
				SUMX(
					sales_sample,
					sales_sample[quantity] * sales_sample[unit_price]
				),
				REMOVEFILTERS(sales_sample[product])
			)
	
		RETURN
			DIVIDE(ProductSales, TotalSalesAllProducts, 0)
		formatString: 0.0%
		lineageTag: 30000000-0000-0000-0000-000000000002

	column order_id
		dataType: string
		lineageTag: 30000000-0000-0000-0000-000000000010
		summarizeBy: none
		sourceColumn: order_id

	column product
		dataType: string
		lineageTag: 30000000-0000-0000-0000-000000000013
		summarizeBy: none
		sourceColumn: product

	column quantity
		dataType: int64
		lineageTag: 30000000-0000-0000-0000-000000000011
		summarizeBy: sum
		sourceColumn: quantity

	column unit_price
		dataType: double
		lineageTag: 30000000-0000-0000-0000-000000000012
		summarizeBy: none
		sourceColumn: unit_price
