/// ============================================================================
/// Exercise 05 - Skills & Slash Commands - MESSY MEASURES
/// ============================================================================
/// This file contains various DAX measures with issues:
/// - No documentation
/// - Inconsistent naming
/// - Potential bugs
/// - Poor formatting
/// Use Copilot's slash commands to clean them up!
/// ============================================================================

table sales_sample

	measure rev = [Total Revenue]
		lineageTag: 50000000-0000-0000-0000-000000000001

	measure AvgOrdVal = DIVIDE([Total Revenue],DISTINCTCOUNT(sales_sample[order_id]))
		lineageTag: 50000000-0000-0000-0000-000000000002

	measure TopProd = CALCULATE([Total Revenue],TOPN(1,ALL(sales_sample[product]),[Total Revenue]))
		lineageTag: 50000000-0000-0000-0000-000000000003

	measure PctGrowth = VAR c=[Total Revenue] VAR p=CALCULATE([Total Revenue],DATEADD(sales_sample[order_date],-1,MONTH)) RETURN (c-p)/p
		lineageTag: 50000000-0000-0000-0000-000000000004

	measure CustomerRev = SUMX(VALUES(sales_sample[customer_id]),CALCULATE([Total Revenue]))
		lineageTag: 50000000-0000-0000-0000-000000000005

	/// This measure has a bug - can you find it?
	measure 'QtyPerOrder' = SUM(sales_sample[quantity])/COUNT(sales_sample[order_id])
		lineageTag: 50000000-0000-0000-0000-000000000006

	measure NorthSales = CALCULATE([Total Revenue],sales_sample[region]="North")
		lineageTag: 50000000-0000-0000-0000-000000000007

	/// What does this measure even do?
	measure X = IF(SELECTEDVALUE(sales_sample[region])="North",[Total Revenue]*1.1,[Total Revenue])
		lineageTag: 50000000-0000-0000-0000-000000000008

	measure cat_rev = SUMX(VALUES(sales_sample[category]),[Total Revenue])
		lineageTag: 50000000-0000-0000-0000-000000000009

	/// Another potential issue here
	measure GrowthPct = ([Total Revenue]-CALCULATE([Total Revenue],DATEADD(sales_sample[order_date],-1,YEAR)))/CALCULATE([Total Revenue],DATEADD(sales_sample[order_date],-1,YEAR))
		lineageTag: 50000000-0000-0000-0000-000000000010
